import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

// * NEXTAUTH - import SessionProvider
import { SessionProvider } from 'next-auth/react'

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <>
      <Head>
        <title>NextAuth.js + Prisma</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* NOTE: NEXTAUTH - wrap the app with SessionProvider */}
      <SessionProvider session={session}>
        <Component {...pageProps} />
      </SessionProvider>
    </>
  )
}
